### PR TITLE
Add createPayloadAction helper function

### PR DESCRIPTION
**Pull request by ascorbic**
Hi. Nice library. I've added a helper function for when you just want to copy the parameters into the payload.

### CODE REVIEW

**Comment by piotrwitek** [comment]
Hi @ascorbic,
Thanks for contribution.
I think this new API idea is too specific and limited in scope of handling different use cases.
My idea with this library is to create a small, more generic and flexible API.

I don't want it to have a bunch of random methods for each use-case, which will grow to a huge and bloated API surface with time.
I would like to achieve small and focused API, but generic enough to handle 95% of use cases, but we'll see and perhaps in the future I will rethink this idea.

Basically your example:
```ts
const notify = createPayloadAction('NOTIFY', {} as NotifyPayload);
```
can be done using universal createAction like this:
```ts
const notify = createAction('NOTIFY', (payload: NotifyPayload) => ({ type: 'NOTIFY', payload }));
```

As you can see a little bit more typing, but also more clean (no type assertion -> which is treated as smell by community: https://palantir.github.io/tslint/rules/no-object-literal-type-assertion/) and more explicit (which is good when thinking using Redux philosophy).

I don't see any good reasons to add this one random function for now, but if you'd like to we can open a discussion/proposal in the issues to design a dedicated set of coherent helper functions to handle some common specific use cases.

**Comment by piotrwitek** [comment]
I think I could improve createAction definition to also allow this usage, which would minimize boilerplate even further:
```ts
const notify = createAction('NOTIFY', (payload: NotifyPayload) => ({ payload }));
```

**Comment by ascorbic** [comment]
That's fair enough. I like the latter version, as I have an aversion to re-typing string literals.

**Comment by piotrwitek** [comment]
Thanks for feedback and some sharing your ideas.

**Pull request closed without merging**
